packages:
  - "apps/*"
  - "packages/*"
  - "agent"
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.62.0'
  - wrangler@4.143.0

overrides:
  esbuild: 0.25.12
